### ISSUE TITLE
java.lang.AssertionError:

### ISSUE THREAD

**Issue by FlinkRonny** [stefan-jung/org.jung.release-notes#1]
The following error is present in the log.txt

`C:\dita-ot-3.0\plugins\org.dita.pdf2\build.xml:281: java.lang.AssertionError: **** Component reference variable retain-bookmap-order is already bound`

Here is my bookmap:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookmap PUBLIC "-//OASIS//DTD DITA BookMap//EN" "bookmap.dtd">
<bookmap>
    <booktitle>
        <mainbooktitle>My new test book</mainbooktitle>
    </booktitle>
    <frontmatter>
        <booklists>
            <toc/>
            <booklist type="change-historylist"/>
        </booklists>
    </frontmatter>
    <chapter href="safety_instructions/c_explanation_of_safety_signs_en_001.dita"/>
</bookmap>
```

Here is my transform:

`dita -i "D:\Workspace\My_new_test_book.ditamap" -f pdf -o "D:\Workspace\Output" -l log.txt -Dchangelist.style=table`

**Comment by stefan-jung** [comment]
@FlinkRonny Could you please publish with the `--verbose` parameter and upload the **log.txt**?

**Comment by FlinkRonny** [comment]
[log.txt](https://github.com/doctales/org.doctales.release-notes/files/1503076/log.txt)

Hi, please find attached log.txt with `--verbose` parameter.

**Comment by stefan-jung** [comment]
Thank you for reporting this @FlinkRonny, the issue should be fixed now. If you need information, please [read the docs](https://doctales.atlassian.net/wiki/x/T4APAw) or [ask a question](https://doctales.atlassian.net/wiki/plugins/servlet/ac/com.atlassian.confluence.plugins.confluence-questions/globalQuestionsViewer).
